import Head from "next/head";
import Banner from "../components/Banner";
import HomeBody from "../components/HomeBody";
import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Moveright</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <Banner />
      </section>
      <section>
        <HomeBody />
      </section>
    </div>
  );
};

export default Home;
